### PR TITLE
Last minute

### PR DESCRIPTION
**Pull request by Kaize-1213**
Request to merge Dendrogram and Heatmap

### CODE REVIEW

**Review by LimZiXuan — DISMISSED** [review]

**Review by mifahmii — DISMISSED** [review]

**Comment by omar-al-hendi** [comment]
Thank you for your contribution @Kaize-1213 
Please resolve the conflicts

**Comment by Ariff271001** [comment]
reviewed

**Review by Ariff271001 — DISMISSED** [review]
reviewed

**Review by omar-al-hendi — DISMISSED** [review]

**Comment by omar-al-hendi** [comment]
image


@Kaize-1213 The branch could not be merged, I think it is because the rebase has not been done succussfully, 
Please rebase from the main branch by doing so:
`git checkout main`
`git pull`
`git checkout <your branch`
`git rebase main`

**Review by sulaimanmhashim — APPROVED** [review]

**Comment by Kaize-1213** [comment]
done solving merge conflict

**Review by LimZiXuan — DISMISSED** [review]

**Review by mifahmii — APPROVED** [review]

**Review by HeLinChooi — DISMISSED** [review]
Great job :)
Later on will put your charts into respective categories.

**Review by omar-al-hendi — APPROVED** [review]

**Pull request merged**
