### PR TITLE
feat: add kpi and balanced board

### PR DESCRIPTION
**Pull request by Leon-Chin**
Add kpi balanced board

### CODE REVIEW

**Review by sulaimanmhashim — DISMISSED** [review]

**Review by omar-al-hendi — APPROVED** [review]

**Comment by omar-al-hendi** [comment]
@Leon-Chin Thanks for your contribution,  please solve the conflicts so we can merge

**Comment by Leon-Chin** [comment]
> 

Thanks, i already sovle the conficts.

**Review by omar-al-hendi — APPROVED** [review]

**Comment by omar-al-hendi** [comment]
Please rebase from the main branch.  
image

**Review by HeLinChooi — APPROVED** [review]

**Comment by HeLinChooi** [comment]
@omar-al-hendi  I think we could go for merging instead of rebasing onto main. In this way they won't need to resolve conflicts on every commit rebased onto main.

**Pull request merged**
